
title: Resume Igor Nikonorov
url: ''
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Igor Nikonorov
tagline: System administrator/DevOps
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: igor.nikonorov@gmail.com
#phone: 012 345 6789
website: inik.tk #do not add http://
linkedin: igor-nikonorov-3784774b
github: nikonorovi
#twitter: '@webjeda'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
